//! Copy vocabulary for the process-insights cards.

#[derive(Clone, Copy)]
pub struct ProcessInsightsLabels {
    pub loading: &'static str,
    pub connections: &'static str,
    pub no_connections: &'static str,
    pub network_throughput: &'static str,
    pub received: &'static str,
    pub sent: &'static str,
    pub gpu: &'static str,
    pub no_gpu: &'static str,
    pub gpu_usage: &'static str,
    pub vram: &'static str,
    pub resource_limits: &'static str,
    pub memory: &'static str,
    pub cpu: &'static str,
    pub pids: &'static str,
    pub resource_group: &'static str,
    pub isolation: &'static str,
    pub container_id: &'static str,
    pub sandboxed: &'static str,
    pub security_profile: &'static str,
    pub seccomp: &'static str,
    pub no_new_privs: &'static str,
    pub ptrace_scope: &'static str,
    pub capabilities: &'static str,
    pub namespaces: &'static str,
    pub sandbox_details: &'static str,
    pub host_process: &'static str,
    pub open_files: &'static str,
    pub no_open_files: &'static str,
    pub unreadable: &'static str,
    pub threads: &'static str,
    pub no_threads: &'static str,
    pub thread_id: &'static str,
    pub thread_name: &'static str,
    pub thread_state: &'static str,
    pub thread_cpu_time: &'static str,
    pub thread_cpu_percent: &'static str,
    pub thread_wait: &'static str,
    pub environment: &'static str,
    pub no_environment: &'static str,
    pub yes: &'static str,
    pub no: &'static str,
    pub unknown: &'static str,
    pub unlimited: &'static str,
    pub healthy: &'static str,
    pub stale: &'static str,
    pub permission_denied: &'static str,
    pub provider_unavailable: &'static str,
    pub unsupported: &'static str,
    pub worker_disconnected: &'static str,
}

impl ProcessInsightsLabels {
    /// Stable English strings reserved for deterministic headless/capture use.
    pub const fn capture_fixture() -> Self {
        Self {
            loading: "Loading process insights…",
            connections: "Connections",
            no_connections: "No active connections",
            network_throughput: "Network throughput",
            received: "Received",
            sent: "Sent",
            gpu: "GPU",
            no_gpu: "No process GPU counters",
            gpu_usage: "Usage",
            vram: "VRAM",
            resource_limits: "Resource limits",
            memory: "Memory",
            cpu: "CPU quota",
            pids: "Processes",
            resource_group: "Resource group",
            isolation: "Isolation",
            container_id: "Container ID",
            sandboxed: "Sandboxed",
            security_profile: "Security profile",
            seccomp: "Seccomp",
            no_new_privs: "No new privileges",
            ptrace_scope: "Ptrace scope",
            capabilities: "Capabilities",
            namespaces: "Namespaces",
            sandbox_details: "Sandbox details",
            host_process: "Host process",
            open_files: "Open files",
            no_open_files: "No readable file descriptors",
            unreadable: "unreadable",
            threads: "Threads",
            no_threads: "No threads",
            thread_id: "TID",
            thread_name: "Name",
            thread_state: "State",
            thread_cpu_time: "CPU time",
            thread_cpu_percent: "CPU %",
            thread_wait: "Wait",
            environment: "Environment variables",
            no_environment: "No environment variables observed",
            yes: "Yes",
            no: "No",
            unknown: "Unknown",
            unlimited: "Unlimited",
            healthy: "Available",
            stale: "Process unavailable",
            permission_denied: "Permission denied",
            provider_unavailable: "Provider unavailable",
            unsupported: "Unsupported by this provider",
            worker_disconnected: "Telemetry worker stopped",
        }
    }
}
