//! Compute-accelerator (NPU) device inventory via SetupAPI.
//!
//! MCDM devices enumerate under the documented
//! `COMPUTE_ACCELERATOR_CLASS_GUID` device-setup class
//! (`{f01a9d53-3ff6-48d2-9f97-c8a7004be10c}`, per the official Microsoft
//! Q&A guidance on reading NPU facts); device properties expose the friendly
//! name and driver description without elevation. Utilization is
//! deliberately NOT read here: the perf-counter set backing Task Manager's
//! NPU columns is undocumented (Microsoft support confirmed the name is not
//! `GPU Engine` and is not public), so utilization stays a typed
//! unavailable fact until an on-box receipt proves a runtime-discovered
//! counter set (ADR-018).

use crate::WindowsApiError;

/// Maximum compute-accelerator devices enumerated per pass; a host with
/// more MCDM devices than this exceeds the product's rendering shape, so
/// the read stays bounded (the same ceiling spirit as the GPU adapters).
const MAX_COMPUTE_ACCELERATORS: u32 = 16;

/// One MCDM compute-accelerator device present on the system.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct WindowsComputeAccelerator {
    /// SetupAPI device instance path (stable identity).
    pub instance_path: String,
    /// Device friendly name (e.g. "Intel(R) AI Boost").
    pub friendly_name: Option<String>,
    /// Driver description from the device's driver key.
    pub driver_desc: Option<String>,
}

/// Enumerate present compute-accelerator (NPU) devices.
#[cfg(windows)]
#[must_use = "inspect the native accelerator enumeration result"]
pub fn enumerate_compute_accelerators() -> Result<Vec<WindowsComputeAccelerator>, WindowsApiError> {
    use windows::Win32::Devices::DeviceAndDriverInstallation::{
        DIGCF_PRESENT, SP_DEVINFO_DATA, SPDRP_DEVICEDESC, SPDRP_FRIENDLYNAME,
        SetupDiEnumDeviceInfo, SetupDiGetClassDevsW,
    };
    use windows::core::{GUID, PCWSTR};

    // COMPUTE_ACCELERATOR_CLASS_GUID `{f01a9d53-3ff6-48d2-9f97-c8a7004be10c}`
    // (devguid.h): the MCDM/WDM compute-accelerator device-setup class NPUs
    // enumerate under; the constant is not generated by the `windows` crate.
    let class_guid = GUID::from_u128(0xf01a9d53_3ff6_48d2_9f97_c8a7004be10c);

    let device_info_set = {
        // SAFETY: `class_guid` is a stack value valid for this synchronous
        // call; no enumerator filter or owner window is requested, and the
        // returned handle is owned by `DeviceInfoSetGuard` below.
        match unsafe {
            SetupDiGetClassDevsW(Some(&class_guid), PCWSTR::null(), None, DIGCF_PRESENT)
        } {
            Ok(set) if !set.is_invalid() => set,
            _ => return Err(WindowsApiError::QueryFailed),
        }
    };
    let _guard = DeviceInfoSetGuard(device_info_set);

    let mut devices = Vec::new();
    for member_index in 0..=MAX_COMPUTE_ACCELERATORS {
        let mut info_data = SP_DEVINFO_DATA {
            cbSize: u32::try_from(core::mem::size_of::<SP_DEVINFO_DATA>())
                .map_err(|_| WindowsApiError::QueryFailed)?,
            ..Default::default()
        };
        // SAFETY: `info_data` is a writable record sized by its `cbSize`
        // field about one member of the owned device-info set; the end of
        // the member list (or any other failure) simply ends the bounded
        // enumeration.
        if unsafe { SetupDiEnumDeviceInfo(device_info_set, member_index, &mut info_data) }.is_err()
        {
            break;
        }
        if member_index == MAX_COMPUTE_ACCELERATORS {
            return Err(WindowsApiError::ResourceLimit);
        }
        let instance_path = device_instance_path(device_info_set, &info_data)?;
        let device_desc = device_registry_string(device_info_set, &info_data, SPDRP_DEVICEDESC);
        // Windows leaves the friendly name unset unless the device was
        // renamed; Device Manager then displays the device description, so
        // mirror that documented fallback instead of a nameless device.
        let friendly_name = device_registry_string(device_info_set, &info_data, SPDRP_FRIENDLYNAME)
            .or(device_desc.clone());
        devices.push(WindowsComputeAccelerator {
            instance_path,
            friendly_name,
            driver_desc: device_desc,
        });
    }
    Ok(devices)
}

/// Non-Windows hosts keep the lane dormant with the typed fallback.
#[cfg(not(windows))]
pub fn enumerate_compute_accelerators() -> Result<Vec<WindowsComputeAccelerator>, WindowsApiError> {
    Err(WindowsApiError::Unsupported)
}

/// Closes the owned SetupAPI device-info-set handle exactly once.
#[cfg(windows)]
struct DeviceInfoSetGuard(windows::Win32::Devices::DeviceAndDriverInstallation::HDEVINFO);

#[cfg(windows)]
impl Drop for DeviceInfoSetGuard {
    fn drop(&mut self) {
        if !self.0.is_invalid() {
            // SAFETY: the guard exclusively owns the handle returned by
            // `SetupDiGetClassDevsW`; Drop runs at most once.
            let _ = unsafe {
                windows::Win32::Devices::DeviceAndDriverInstallation::SetupDiDestroyDeviceInfoList(
                    self.0,
                )
            };
        }
    }
}

/// Widest device instance path Windows defines (`MAX_DEVICE_ID_LEN`,
/// NUL included).
#[cfg(windows)]
const MAX_INSTANCE_ID_UTF16: usize = 200;

/// Widest device property string read per device (256 UTF-16 units, NUL
/// included).
#[cfg(windows)]
const MAX_DEVICE_PROPERTY_UTF16: usize = 256;

/// The stable device instance path (e.g. `ACPI\INTC1070\1`) of one
/// enumerated member. A member without a decodable, non-empty instance id
/// is not a usable identity and fails the enumeration typedly.
#[cfg(windows)]
fn device_instance_path(
    device_info_set: windows::Win32::Devices::DeviceAndDriverInstallation::HDEVINFO,
    info_data: &windows::Win32::Devices::DeviceAndDriverInstallation::SP_DEVINFO_DATA,
) -> Result<String, WindowsApiError> {
    use windows::Win32::Devices::DeviceAndDriverInstallation::SetupDiGetDeviceInstanceIdW;

    let mut buffer = [0_u16; MAX_INSTANCE_ID_UTF16];
    // SAFETY: `buffer` is a writable `MAX_DEVICE_ID_LEN`-capacity UTF-16
    // buffer kept alive for this synchronous call against the enumerated
    // member; the required-size out-param is not needed because the
    // documented maximum is bounded.
    unsafe { SetupDiGetDeviceInstanceIdW(device_info_set, info_data, Some(&mut buffer), None) }
        .map_err(|_| WindowsApiError::QueryFailed)?;
    let end = buffer
        .iter()
        .position(|&unit| unit == 0)
        .unwrap_or(buffer.len());
    let decoded = String::from_utf16(&buffer[..end]).map_err(|_| WindowsApiError::InvalidText)?;
    if decoded.is_empty() {
        return Err(WindowsApiError::QueryFailed);
    }
    Ok(decoded)
}

/// One REG_SZ device property (e.g. `SPDRP_FRIENDLYNAME`), decoded to a
/// trimmed string. `None` is the honest optional absence: the property is
/// unset, undecodable, or empty — never a reason to fail the enumeration
/// or fabricate a label.
#[cfg(windows)]
fn device_registry_string(
    device_info_set: windows::Win32::Devices::DeviceAndDriverInstallation::HDEVINFO,
    info_data: &windows::Win32::Devices::DeviceAndDriverInstallation::SP_DEVINFO_DATA,
    property: windows::Win32::Devices::DeviceAndDriverInstallation::SETUP_DI_REGISTRY_PROPERTY,
) -> Option<String> {
    use windows::Win32::Devices::DeviceAndDriverInstallation::SetupDiGetDeviceRegistryPropertyW;

    let mut buffer = [0_u8; MAX_DEVICE_PROPERTY_UTF16 * 2];
    // SAFETY: `buffer` is a writable byte buffer sized for one REG_SZ
    // property value, kept alive for this synchronous call; the registry
    // data-type out-param is deliberately ignored because only REG_SZ
    // properties are requested.
    let read = unsafe {
        SetupDiGetDeviceRegistryPropertyW(
            device_info_set,
            info_data,
            property,
            None,
            Some(&mut buffer),
            None,
        )
    };
    if read.is_err() {
        return None;
    }
    let mut units = Vec::with_capacity(MAX_DEVICE_PROPERTY_UTF16);
    for pair in buffer.as_chunks::<2>().0 {
        let unit = u16::from_le_bytes(*pair);
        if unit == 0 {
            break;
        }
        units.push(unit);
    }
    let decoded = String::from_utf16(&units).ok()?;
    let trimmed = decoded.trim();
    (!trimmed.is_empty()).then(|| trimmed.to_string())
}
