//! Strict capture scenario tokens and readiness-marker gates.

mod runtime;
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CaptureScenario {
    SmartMissingTool,
    SmartPermission,
    DeviceHotplug,
    GpuEngineInventory,
    IntelGpuTelemetry,
    ProcessForceKill,
    ProcessSelection,
    ProcessMemoryPssSwap,
    ProcessPropertiesPerformance,
    ProcessTreeConfirm,
    ProcessBatchConfirm,
    ServiceDetailsLogs,
    StartupImpact,
    StartupFailureEvidence,
    StartupBootMarkers,
    DiagnosticPreview,
    DiagnosticFailure,
    ActiveAlert,
    SystemDashboard,
    SystemHardware,
    SystemNpu,
    HistorySixtyMinutes,
    AlertRulesManager,
    EventCenter,
    SavedViewPresets,
    ProcessNetworkDetails,
    ProcessGpuDetails,
    ProcessResourceLimits,
    ProcessIsolation,
    StorageHealth,
    SmartSelfTestConfirm,
    SensorCenter,
    BatteryFanPerformance,
    BatteryLivePerformance,
    PartitionDiskUsage,
    PartitionLiveUsage,
    KeyboardFocus,
    VerticalNav,
    SettingsSwitchFocus,
    SettingsZeroGray,
    SettingsPermissionCenter,
    AppsSearchHighlight,
    ServicesSearchHighlight,
    AppsZeroGray,
    AppsGroupExpanded,
    AppsIdentityMatrix,
    SidebarHidden,
    SidebarEdit,
    TelemetryPaused,
    SystemAbout,
    About,
    FirstRun,
    HistoryReplay,
    ApplicationHistoryReplay,
}

impl CaptureScenario {
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "smart-missing-tool" => Some(Self::SmartMissingTool),
            "smart-permission" => Some(Self::SmartPermission),
            "device-hotplug" => Some(Self::DeviceHotplug),
            "gpu-engine-inventory" => Some(Self::GpuEngineInventory),
            "intel-gpu-telemetry" => Some(Self::IntelGpuTelemetry),
            "process-force-kill" => Some(Self::ProcessForceKill),
            "process-selection" => Some(Self::ProcessSelection),
            "process-memory-pss-swap" => Some(Self::ProcessMemoryPssSwap),
            "process-properties-performance" => Some(Self::ProcessPropertiesPerformance),
            "process-tree-confirm" => Some(Self::ProcessTreeConfirm),
            "process-batch-confirm" => Some(Self::ProcessBatchConfirm),
            "service-details-logs" => Some(Self::ServiceDetailsLogs),
            "startup-impact" => Some(Self::StartupImpact),
            "startup-failure-evidence" => Some(Self::StartupFailureEvidence),
            "startup-boot-markers" => Some(Self::StartupBootMarkers),
            "diagnostic-preview" => Some(Self::DiagnosticPreview),
            "diagnostic-failure" => Some(Self::DiagnosticFailure),
            "active-alert" => Some(Self::ActiveAlert),
            "system-dashboard" => Some(Self::SystemDashboard),
            "system-hardware" => Some(Self::SystemHardware),
            "system-npu" => Some(Self::SystemNpu),
            "history-60m" => Some(Self::HistorySixtyMinutes),
            "alert-rules-manager" => Some(Self::AlertRulesManager),
            "event-center" => Some(Self::EventCenter),
            "saved-view-presets" => Some(Self::SavedViewPresets),
            "process-network-details" => Some(Self::ProcessNetworkDetails),
            "process-gpu-details" => Some(Self::ProcessGpuDetails),
            "process-resource-limits" => Some(Self::ProcessResourceLimits),
            "process-isolation" => Some(Self::ProcessIsolation),
            "storage-health" => Some(Self::StorageHealth),
            "smart-self-test-confirm" => Some(Self::SmartSelfTestConfirm),
            "sensor-center" => Some(Self::SensorCenter),
            "battery-fan-performance" => Some(Self::BatteryFanPerformance),
            "battery-live-performance" => Some(Self::BatteryLivePerformance),
            "partition-disk-usage" => Some(Self::PartitionDiskUsage),
            "partition-live-usage" => Some(Self::PartitionLiveUsage),
            "keyboard-focus" => Some(Self::KeyboardFocus),
            "vertical-nav" => Some(Self::VerticalNav),
            "settings-switch-focus" => Some(Self::SettingsSwitchFocus),
            "settings-zero-gray" => Some(Self::SettingsZeroGray),
            "settings-permission-center" => Some(Self::SettingsPermissionCenter),
            "apps-search-highlight" => Some(Self::AppsSearchHighlight),
            "services-search-highlight" => Some(Self::ServicesSearchHighlight),
            "apps-zero-gray" => Some(Self::AppsZeroGray),
            "apps-group-expanded" => Some(Self::AppsGroupExpanded),
            "apps-identity-matrix" => Some(Self::AppsIdentityMatrix),
            "sidebar-hidden" => Some(Self::SidebarHidden),
            "sidebar-edit" => Some(Self::SidebarEdit),
            "telemetry-paused" => Some(Self::TelemetryPaused),
            "system-about" => Some(Self::SystemAbout),
            "about" => Some(Self::About),
            "first-run" => Some(Self::FirstRun),
            "history-replay" => Some(Self::HistoryReplay),
            "application-history-replay" => Some(Self::ApplicationHistoryReplay),
            _ => None,
        }
    }

    pub fn token(self) -> &'static str {
        match self {
            Self::SmartMissingTool => "smart-missing-tool",
            Self::SmartPermission => "smart-permission",
            Self::DeviceHotplug => "device-hotplug",
            Self::GpuEngineInventory => "gpu-engine-inventory",
            Self::IntelGpuTelemetry => "intel-gpu-telemetry",
            Self::ProcessForceKill => "process-force-kill",
            Self::ProcessSelection => "process-selection",
            Self::ProcessMemoryPssSwap => "process-memory-pss-swap",
            Self::ProcessPropertiesPerformance => "process-properties-performance",
            Self::ProcessTreeConfirm => "process-tree-confirm",
            Self::ProcessBatchConfirm => "process-batch-confirm",
            Self::ServiceDetailsLogs => "service-details-logs",
            Self::StartupImpact => "startup-impact",
            Self::StartupFailureEvidence => "startup-failure-evidence",
            Self::StartupBootMarkers => "startup-boot-markers",
            Self::DiagnosticPreview => "diagnostic-preview",
            Self::DiagnosticFailure => "diagnostic-failure",
            Self::ActiveAlert => "active-alert",
            Self::SystemDashboard => "system-dashboard",
            Self::SystemHardware => "system-hardware",
            Self::SystemNpu => "system-npu",
            Self::HistorySixtyMinutes => "history-60m",
            Self::AlertRulesManager => "alert-rules-manager",
            Self::EventCenter => "event-center",
            Self::SavedViewPresets => "saved-view-presets",
            Self::ProcessNetworkDetails => "process-network-details",
            Self::ProcessGpuDetails => "process-gpu-details",
            Self::ProcessResourceLimits => "process-resource-limits",
            Self::ProcessIsolation => "process-isolation",
            Self::StorageHealth => "storage-health",
            Self::SmartSelfTestConfirm => "smart-self-test-confirm",
            Self::SensorCenter => "sensor-center",
            Self::BatteryFanPerformance => "battery-fan-performance",
            Self::BatteryLivePerformance => "battery-live-performance",
            Self::PartitionDiskUsage => "partition-disk-usage",
            Self::PartitionLiveUsage => "partition-live-usage",
            Self::KeyboardFocus => "keyboard-focus",
            Self::VerticalNav => "vertical-nav",
            Self::SettingsSwitchFocus => "settings-switch-focus",
            Self::SettingsZeroGray => "settings-zero-gray",
            Self::SettingsPermissionCenter => "settings-permission-center",
            Self::AppsSearchHighlight => "apps-search-highlight",
            Self::ServicesSearchHighlight => "services-search-highlight",
            Self::AppsZeroGray => "apps-zero-gray",
            Self::AppsGroupExpanded => "apps-group-expanded",
            Self::AppsIdentityMatrix => "apps-identity-matrix",
            Self::SidebarHidden => "sidebar-hidden",
            Self::SidebarEdit => "sidebar-edit",
            Self::TelemetryPaused => "telemetry-paused",
            Self::SystemAbout => "system-about",
            Self::About => "about",
            Self::FirstRun => "first-run",
            Self::HistoryReplay => "history-replay",
            Self::ApplicationHistoryReplay => "application-history-replay",
        }
    }

    pub(super) fn is_process_insights(self) -> bool {
        matches!(
            self,
            Self::ProcessNetworkDetails
                | Self::ProcessGpuDetails
                | Self::ProcessResourceLimits
                | Self::ProcessIsolation
        )
    }
}
