[package]
name = "taskmanager-afpacket-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
taskmanager-afpacket = { path = ".." }

[[bin]]
name = "five_tuple"
path = "fuzz_targets/five_tuple.rs"
test = false
doc = false
bench = false

[workspace]
